# stable
newline_style = "unix"
hard_tabs = false
tab_spaces = 4

# unstable
fn_single_line = true
format_code_in_doc_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 20
struct_lit_single_line = true
imports_granularity = "Crate"